//UM ARQUIVO PARA INCLUIR OS DEMAIS ARQUIVOS DO PROJETO DE IMPLEMENTAÇÃO DE HASH_TABLES

/*CABEÇALHO*/
#include"hash_table_theory.hpp"//ARQUIVO CONTENDO A TEORIA DE HASH TABLES E HASH FUNCTIONS
#include"hash_global_variables.hpp"//VARIÁVEIS GLOBAIS USADAS NO PROJETO
#include"hash_function.hpp"//ARQUIVO CONTENDO PROTÓTIPO DE FUNÇÃO HASH
#include"hash_table.hpp"//ARQUIVO CONTENDO A IMPLEMENTAÇÃO DA CLASSE DE HASH TABLES

